# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-ZH-Toke
version:      0.02
version_from: lib/Lingua/ZH/Toke.pm
installdirs:  site
requires:
    Lingua::ZH::TaBE:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
